# fly.toml app configuration file generated for smoke-test-still-sun-8916 on 2025-03-30T16:12:14-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'smoke-test-still-sun-8916'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 10000

  [[services.ports]]
    port = 10000

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[[services]]
  protocol = 'tcp'
  internal_port = 10001

  [[services.ports]]
    port = 10001

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[[vm]]
  size = 'shared-cpu-1x'
